export enum RootPath {
  class = 'class',
  countries = 'countries',
  course = 'course',
  courses = 'courses',
  degrees = 'degrees',
  login = 'login',
  logout = 'logout',
  message = 'message',
  profile = 'profile',
  signUp = 'signup',
  statistics = 'statistics',
  student = 'student',
  students = 'students',
  teacher = 'teacher',
  teachers = 'teachers',
  userRole = 'userRole',
}

export enum SubPath {
  add = 'add',
  update = 'update',
  delete = 'delete',
  code = 'code',
  type = 'type',
  schedule = 'schedule',
  overview = 'overview',
  interest = 'interest',
  statistics = 'statistics',
}
